CREATE TABLE IF NOT EXISTS output_state (
    device_id VARCHAR(100) PRIMARY KEY REFERENCES devices(device_id) ON DELETE CASCADE,
    r1 BOOLEAN NOT NULL DEFAULT FALSE,
    r2 BOOLEAN NOT NULL DEFAULT FALSE,
    r3 BOOLEAN NOT NULL DEFAULT FALSE,
    r4 BOOLEAN NOT NULL DEFAULT FALSE,
    r5 BOOLEAN NOT NULL DEFAULT FALSE,
    r6 BOOLEAN NOT NULL DEFAULT FALSE,
    r7 BOOLEAN NOT NULL DEFAULT FALSE,
    r8 BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
